"""empty message

Revision ID: 33b3c3b7e493
Revises: 
Create Date: 2025-05-24 03:40:07.424196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33b3c3b7e493'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_token', sa.String(length=256), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_payment_token'), ['payment_token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_payment_token'))
        batch_op.drop_column('payment_token')

    # ### end Alembic commands ###
