"""empty message

Revision ID: 5c91883ef0c8
Revises: abf5f80ea20d
Create Date: 2025-05-29 16:35:23.093140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c91883ef0c8'
down_revision = 'abf5f80ea20d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.drop_column('processor')
        batch_op.drop_column('storage')
        batch_op.drop_column('ram')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('generation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('storage_type', postgresql.ENUM('HDD', 'SSD', name='storagetype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ram', postgresql.ENUM('RAM_2GB', 'RAM_4GB', 'RAM_8GB', 'RAM_16GB', 'RAM_32GB', name='ramtype'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('storage', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('processor', postgresql.ENUM('Intel_Core_i3', 'Intel_Core_i5', 'Intel_Core_i7', 'Intel_Core_i9', name='processortype'), autoincrement=False, nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('product_specs')
    # ### end Alembic commands ###
