"""empty message

Revision ID: 85ed0d4b84ed
Revises: 
Create Date: 2025-05-15 19:18:21.564364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ed0d4b84ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('brand', sa.String(length=20), nullable=False),
    sa.Column('last4', sa.String(length=4), nullable=False),
    sa.Column('exp_month', sa.Integer(), nullable=False),
    sa.Column('exp_year', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('enc_pan', sa.LargeBinary(), nullable=False),
    sa.Column('pan_nonce', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_method_order_id'), ['order_id'], unique=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('session_id', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_order_session_id'), ['session_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('total_amount')
        batch_op.drop_column('email')

    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('product_price')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('product_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_column('price')
        batch_op.drop_column('name')
        batch_op.drop_column('product_id')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_order_session_id'))
        batch_op.drop_column('payment_method')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('total')
        batch_op.drop_column('phone')
        batch_op.drop_column('address')
        batch_op.drop_column('session_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('name')

    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_method_order_id'))

    op.drop_table('payment_method')
    # ### end Alembic commands ###
