"""Add masked_pan to PaymentMethod

Revision ID: efb113f6626f
Revises: 33b3c3b7e493
Create Date: 2025-05-24 16:44:30.157744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb113f6626f'
down_revision = '33b3c3b7e493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.add_column(sa.Column('key_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('masked_pan', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_method', schema=None) as batch_op:
        batch_op.drop_column('masked_pan')
        batch_op.drop_column('key_version')

    # ### end Alembic commands ###
