"""empty message

Revision ID: a9e5bf56fa4e
Revises: 1ca3f291ed1d
Create Date: 2025-05-29 11:16:28.308254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9e5bf56fa4e'
down_revision = '1ca3f291ed1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('ram')
        batch_op.drop_column('storage')
        batch_op.drop_column('storage_type')
        batch_op.drop_column('processor')
        batch_op.drop_column('generation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('processor', sa.VARCHAR(length=13), nullable=False))
        batch_op.add_column(sa.Column('storage_type', sa.VARCHAR(length=3), nullable=False))
        batch_op.add_column(sa.Column('storage', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('ram', sa.VARCHAR(length=8), nullable=False))
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    op.drop_table('product_specs')
    # ### end Alembic commands ###
