"""empty message

Revision ID: 1fa32c8afa23
Revises: 5591fbbb41d3
Create Date: 2025-04-24 12:06:12.130759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fa32c8afa23'
down_revision = '5591fbbb41d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_featured', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=100), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_featured')

    # ### end Alembic commands ###
